name: chat_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  sqflite_common_ffi: ^2.3.3+1
  

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
